# Generated by Django 4.2.1 on 2023-06-04 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentapp', '0005_remove_incident_user_incident_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='Incident_status',
            field=models.CharField(choices=[('open', 'Open'), ('progress', 'In progres'), ('closed', 'Closed')], default='open', max_length=50),
        ),
        migrations.AlterField(
            model_name='incident',
            name='reported_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 4, 16, 4, 49, 463241)),
        ),
    ]
