# Generated by Django 4.2.1 on 2023-06-04 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentapp', '0006_alter_incident_incident_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='incident_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='reported_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 4, 16, 29, 51, 87131)),
        ),
    ]
